/**
 * A Windows `.ico`, from the PNGs this package already ships — WP-62.
 *
 * `deckhq shortcut --install` writes a `.lnk`, and a `.lnk` with no icon gets
 * whatever Windows picks for `node.exe`. The product has a mark
 * (`public/icon-512.png`, generated by `scripts/make-pwa-icons.mjs` from the
 * floor's own palette) and Explorer wants it in ICO form.
 *
 * **No dependency, and none is needed**, because an ICO is barely a format: a
 * six-byte directory header, one sixteen-byte entry per image, and then the
 * images. Since Windows Vista an entry's payload may be **a PNG file, byte for
 * byte** rather than a DIB, so this module never decodes, resamples or
 * re-encodes anything — it reads the width and height out of each PNG's IHDR
 * and concatenates. `docs/plan/08-PLAN-V2-100X.md` §1.1 rule 3.
 *
 * THE ONE WART IN THE FORMAT. Width and height in a directory entry are single
 * bytes, and `0` means "256 or larger — read the image's own header". A 512x512
 * PNG therefore has to be declared as `0`, and there is no way to declare it as
 * 512; every PNG→ICO converter does exactly this. So the file this writes
 * carries **two** entries, 192 (declared exactly, no sentinel involved) and 512
 * (declared `0`), and Windows picks whichever is closer to the size it is
 * drawing. The small-icon case — the 16x16 in a Start Menu list — is served by
 * the 192, where the sentinel plays no part at all.
 *
 * Nothing here touches the disk. `pngToIco` takes buffers and returns one.
 */

/** The eight bytes every PNG starts with. */
const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

/** Bytes in one `ICONDIRENTRY`. */
export const ENTRY_BYTES = 16;

/** Bytes in the `ICONDIR` header that precedes them. */
export const HEADER_BYTES = 6;

/**
 * The pixel size a PNG declares in its IHDR, or null when the buffer is not a
 * PNG. Never throws: `shortcut --install` degrades to no icon rather than
 * failing over an unreadable asset.
 *
 * @param {Buffer|Uint8Array} bytes
 * @returns {{width:number, height:number}|null}
 */
export function pngSize(bytes) {
  const buf = Buffer.isBuffer(bytes) ? bytes : Buffer.from(bytes || []);
  // 8 magic + 4 length + 4 "IHDR" + 8 dimensions
  if (buf.length < 24) return null;
  if (!buf.subarray(0, 8).equals(PNG_MAGIC)) return null;
  if (buf.toString('latin1', 12, 16) !== 'IHDR') return null;
  const width = buf.readUInt32BE(16);
  const height = buf.readUInt32BE(20);
  if (!width || !height) return null;
  return { width, height };
}

/**
 * One `.ico` holding every PNG given, largest first.
 *
 * @param {Array<Buffer|Uint8Array>} pngs
 * @returns {Buffer}
 * @throws when no argument is a readable PNG — the caller then writes no icon
 *         and says so, rather than writing a file Explorer cannot open.
 */
export function pngToIco(pngs) {
  const images = [];
  for (const png of pngs || []) {
    const buf = Buffer.isBuffer(png) ? png : Buffer.from(png || []);
    const size = pngSize(buf);
    if (size) images.push({ buf, ...size });
  }
  if (images.length === 0) throw new Error('no readable PNG was given to pngToIco');
  // Largest first: Windows walks the directory in order looking for the best
  // match, and every reference implementation writes them descending.
  images.sort((a, b) => b.width * b.height - a.width * a.height);

  const header = Buffer.alloc(HEADER_BYTES);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // 1 = icon (2 would be a cursor)
  header.writeUInt16LE(images.length, 4);

  let offset = HEADER_BYTES + ENTRY_BYTES * images.length;
  const entries = [];
  for (const image of images) {
    const entry = Buffer.alloc(ENTRY_BYTES);
    // See the header: 0 is the "256 or larger" sentinel, and 256 itself is
    // also written as 0 because 256 does not fit in a byte.
    entry.writeUInt8(image.width >= 256 ? 0 : image.width, 0);
    entry.writeUInt8(image.height >= 256 ? 0 : image.height, 1);
    entry.writeUInt8(0, 2); // colours in the palette; 0 for truecolour
    entry.writeUInt8(0, 3); // reserved
    entry.writeUInt16LE(1, 4); // colour planes
    entry.writeUInt16LE(32, 6); // bits per pixel — the PNGs are RGBA
    entry.writeUInt32LE(image.buf.length, 8);
    entry.writeUInt32LE(offset, 12);
    entries.push(entry);
    offset += image.buf.length;
  }

  return Buffer.concat([header, ...entries, ...images.map((i) => i.buf)]);
}

/**
 * Read an ICO back as data — the directory only, never the images.
 *
 * Exists for the test, and for `shortcut --install` to check its own output
 * before it tells the user an icon was written: an ICO whose entries point
 * outside the file is one Explorer draws as a blank page, and finding that out
 * here costs nothing.
 *
 * @param {Buffer|Uint8Array} bytes
 * @returns {{type:number, count:number,
 *            entries:Array<{width:number, height:number, bytes:number,
 *                           offset:number, png:boolean}>}|null}
 */
export function readIco(bytes) {
  const buf = Buffer.isBuffer(bytes) ? bytes : Buffer.from(bytes || []);
  if (buf.length < HEADER_BYTES) return null;
  if (buf.readUInt16LE(0) !== 0) return null;
  const type = buf.readUInt16LE(2);
  const count = buf.readUInt16LE(4);
  if (type !== 1 && type !== 2) return null;
  if (count < 1 || buf.length < HEADER_BYTES + ENTRY_BYTES * count) return null;

  const entries = [];
  for (let i = 0; i < count; i++) {
    const at = HEADER_BYTES + ENTRY_BYTES * i;
    const declaredW = buf.readUInt8(at);
    const declaredH = buf.readUInt8(at + 1);
    const size = buf.readUInt32LE(at + 8);
    const offset = buf.readUInt32LE(at + 12);
    if (offset + size > buf.length) return null;
    const payload = buf.subarray(offset, offset + size);
    const real = pngSize(payload);
    entries.push({
      // The sentinel resolved: what the entry says, or what the PNG says when
      // the entry could not say it.
      width: declaredW === 0 ? (real?.width ?? 256) : declaredW,
      height: declaredH === 0 ? (real?.height ?? 256) : declaredH,
      bytes: size,
      offset,
      png: real != null,
    });
  }
  return { type, count, entries };
}
